services:
  small_linkedin:
    container_name: link-go
    image: "bitnami/postgresql:15"
    environment:
      - POSTGRES_USER=link
      - POSTGRES_PASSWORD=link
      - POSTGRES_DB=link
    ports:
      - "5432:5432"
    volumes:
      - link:/var/lib/postgresql/data

volumes:
  link:
